### ISSUE TITLE
插件加载出错

### ISSUE THREAD

**Issue by PackageInstaller** [Agnes4m/nonebot_plugin_AL#5]
报错以及插件目录结构如下
![image](https://github.com/Agnes4m/nonebot_plugin_AL/assets/80018096/49c68559-ffaf-48c8-8377-3489ca4a3856)
![image](https://github.com/Agnes4m/nonebot_plugin_AL/assets/80018096/c4193cbf-92c1-4903-8694-818cb2898a51)

**Comment by Agnes4m** [comment]
更新版本即可

**Comment by PackageInstaller** [comment]
![image](https://github.com/Agnes4m/nonebot_plugin_AL/assets/80018096/60dacc80-8acc-4005-8938-33da15be4c86)

**Comment by PackageInstaller** [comment]
最近搭上qsign又玩bot了，直接删去__init__.py,把整个nonebot_plugin_al里面的文件都移出来就加载了，虽然到现在也不知道那加载插件语句哪里错了
