### ISSUE TITLE
查询出错,[Errno 2] No such file or directory: 'data/al/azurapi_data/names.json'

### ISSUE THREAD

**Issue by niucattle** [Agnes4m/nonebot_plugin_AL#6]
blhx查询的相关指令基本都报这个错  是我配置哪里漏了吗
![W9)}_ CMP1(V ~__D )FE2R](https://github.com/Agnes4m/nonebot_plugin_AL/assets/118875129/759174de-58e6-4580-b246-057a5f030ccd)
![}MV TIM)I@2RE%(BQ00{$~Y](https://github.com/Agnes4m/nonebot_plugin_AL/assets/118875129/3ae63b29-71c5-4c4e-aab2-a2820c8485a9)

**Comment by niucattle** [comment]
而且我看al目录下就没azurapi_data这个文件夹

**Comment by Agnes4m** [comment]
https://github.com/Agnes4m/nonebot_plugin_AL#%E8%B5%84%E6%BA%90%E5%8C%85

此外，`blhx 强制更新`指令可以强制生成这个文件，针对所展示的指令
